packages:
  - packages/*
  - test/*

catalog:
  '@babel/core': ^7.28.4
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.7
  '@rollup/plugin-babel': ^6.0.4
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-terser': 0.4.4
  '@taiyuuki/eslint-config': ^1.5.6
  '@types/node': ^22.18.6
  '@types/pako': ^2.0.4
  '@types/prompts': ^2.4.9
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.2
  '@vitejs/plugin-vue': ^6.0.1
  eslint: ^9.36.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  kolorist: ^1.8.0
  prompts: ^2.4.2
  react: ^19.1.1
  react-dom: ^19.1.1
  rimraf: ^6.0.1
  rollup: ^4.52.0
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-delete: ^3.0.1
  rollup-plugin-dts: ^6.2.3
  rollup-plugin-glob-import: ^0.5.0
  rollup-plugin-node-builtins: ^2.1.2
  rollup-plugin-node-globals: ^1.4.0
  rollup-plugin-typescript2: ^0.36.0
  typescript: ^5.9.2
  vite: ^7.1.6
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-tsc: ^3.0.7
