// 该文件由 rollup-plugin-mapper-index 自动生成，请勿手动修改

// 动态导入所有Mapper列表
import type { Mapper } from './Mapper'

type DynamicImport<T> = ()=> Promise<{ default: T }>

export const dynamicMappers: Record<string, DynamicImport<typeof Mapper>> = {
    Action52Mapper: () => import('./MapperList/Action52Mapper'),
    AfterburnerMapper: () => import('./MapperList/AfterburnerMapper'),
    AnromMapper: () => import('./MapperList/AnromMapper'),
    BandaiMapper: () => import('./MapperList/BandaiMapper'),
    CaltronMapper: () => import('./MapperList/CaltronMapper'),
    CnromMapper: () => import('./MapperList/CnromMapper'),
    CodemastersMapper: () => import('./MapperList/CodemastersMapper'),
    ColorDreamsMapper: () => import('./MapperList/ColorDreamsMapper'),
    CrazyClimberMapper: () => import('./MapperList/CrazyClimberMapper'),
    CrimeBustersMapper: () => import('./MapperList/CrimeBustersMapper'),
    FME7Mapper: () => import('./MapperList/FME7Mapper'),
    GnromMapper: () => import('./MapperList/GnromMapper'),
    IremH3001Mapper: () => import('./MapperList/IremH3001Mapper'),
    MIMICMapper: () => import('./MapperList/MIMICMapper'),
    MMC1Mapper: () => import('./MapperList/MMC1Mapper'),
    MMC2Mapper: () => import('./MapperList/MMC2Mapper'),
    MMC3Mapper: () => import('./MapperList/MMC3Mapper'),
    MMC4Mapper: () => import('./MapperList/MMC4Mapper'),
    MMC5Mapper: () => import('./MapperList/MMC5Mapper'),
    MMC6Mapper: () => import('./MapperList/MMC6Mapper'),
    Mapper107: () => import('./MapperList/Mapper107'),
    Mapper112: () => import('./MapperList/Mapper112'),
    Mapper115: () => import('./MapperList/Mapper115'),
    Mapper118: () => import('./MapperList/Mapper118'),
    Mapper119: () => import('./MapperList/Mapper119'),
    Mapper140: () => import('./MapperList/Mapper140'),
    Mapper15: () => import('./MapperList/Mapper15'),
    Mapper152: () => import('./MapperList/Mapper152'),
    Mapper18: () => import('./MapperList/Mapper18'),
    Mapper182: () => import('./MapperList/Mapper182'),
    Mapper185: () => import('./MapperList/Mapper185'),
    Mapper195: () => import('./MapperList/Mapper195'),
    Mapper200: () => import('./MapperList/Mapper200'),
    Mapper201: () => import('./MapperList/Mapper201'),
    Mapper203: () => import('./MapperList/Mapper203'),
    Mapper212: () => import('./MapperList/Mapper212'),
    Mapper213: () => import('./MapperList/Mapper213'),
    Mapper225: () => import('./MapperList/Mapper225'),
    Mapper226: () => import('./MapperList/Mapper226'),
    Mapper229: () => import('./MapperList/Mapper229'),
    Mapper231: () => import('./MapperList/Mapper231'),
    Mapper240: () => import('./MapperList/Mapper240'),
    Mapper241: () => import('./MapperList/Mapper241'),
    Mapper242: () => import('./MapperList/Mapper242'),
    Mapper244: () => import('./MapperList/Mapper244'),
    Mapper245: () => import('./MapperList/Mapper245'),
    Mapper246: () => import('./MapperList/Mapper246'),
    Mapper249: () => import('./MapperList/Mapper249'),
    Mapper255: () => import('./MapperList/Mapper255'),
    Mapper31: () => import('./MapperList/Mapper31'),
    Mapper33: () => import('./MapperList/Mapper33'),
    Mapper34: () => import('./MapperList/Mapper34'),
    Mapper36: () => import('./MapperList/Mapper36'),
    Mapper47: () => import('./MapperList/Mapper47'),
    Mapper48: () => import('./MapperList/Mapper48'),
    Mapper58: () => import('./MapperList/Mapper58'),
    Mapper6: () => import('./MapperList/Mapper6'),
    Mapper60: () => import('./MapperList/Mapper60'),
    Mapper61: () => import('./MapperList/Mapper61'),
    Mapper62: () => import('./MapperList/Mapper62'),
    Mapper67: () => import('./MapperList/Mapper67'),
    Mapper70: () => import('./MapperList/Mapper70'),
    Mapper72: () => import('./MapperList/Mapper72'),
    Mapper74: () => import('./MapperList/Mapper74'),
    Mapper74V2: () => import('./MapperList/Mapper74V2'),
    Mapper76: () => import('./MapperList/Mapper76'),
    Mapper78: () => import('./MapperList/Mapper78'),
    Mapper86: () => import('./MapperList/Mapper86'),
    Mapper87: () => import('./MapperList/Mapper87'),
    Mapper92: () => import('./MapperList/Mapper92'),
    Mapper94: () => import('./MapperList/Mapper94'),
    Mapper97: () => import('./MapperList/Mapper97'),
    NamcoMapper: () => import('./MapperList/NamcoMapper'),
    Namcot34x3Mapper: () => import('./MapperList/Namcot34x3Mapper'),
    Nina003006Mapper: () => import('./MapperList/Nina003006Mapper'),
    NromMapper: () => import('./MapperList/NromMapper'),
    Sunsoft01Mapper: () => import('./MapperList/Sunsoft01Mapper'),
    Sunsoft02Mapper: () => import('./MapperList/Sunsoft02Mapper'),
    Sunsoft03Mapper: () => import('./MapperList/Sunsoft03Mapper'),
    TengenRamboMapper: () => import('./MapperList/TengenRamboMapper'),
    UnromMapper: () => import('./MapperList/UnromMapper'),
    VRC1Mapper: () => import('./MapperList/VRC1Mapper'),
    VRC2Mapper: () => import('./MapperList/VRC2Mapper'),
    VRC3Mapper: () => import('./MapperList/VRC3Mapper'),
    VRC4Mapper: () => import('./MapperList/VRC4Mapper'),
    VRC6Mapper: () => import('./MapperList/VRC6Mapper'),
    VRC7Mapper: () => import('./MapperList/VRC7Mapper'),
}

